name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: jdx/mise-action@v2
        with:
          install_args: bats@latest

      - name: Install dependencies
        run: bun install

      # TODO: the order should be format, typechecks, lint, unit, e2e to fail early
      - name: Run unit tests
        run: bun test

      - name: Run e2e tests
        run: bun run test:e2e

      - name: Lint
        run: bun run lint

      - name: Format check
        run: bun run format:check
